"""Add payment_type and season_id to Payment, make trip_id nullable

Revision ID: 104d18e6f8fb
Revises: 481438e8cbc5
Create Date: 2025-12-02 15:01:34.901135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104d18e6f8fb'
down_revision = '481438e8cbc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        # Add payment_type with default 'trip' for existing records
        batch_op.add_column(sa.Column('payment_type', sa.String(length=50), nullable=False, server_default='trip'))
        batch_op.add_column(sa.Column('season_id', sa.Integer(), nullable=True))
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_payments_season_id', 'seasons', ['season_id'], ['id'])

    # Remove the server default after migration (optional, keeps model clean)
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_type', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_season_id', type_='foreignkey')
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('season_id')
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
