"""Add coach review workflow fields to Practice

Revision ID: 344117c080a7
Revises: 80da5235b382
Create Date: 2025-12-29 02:19:43.100495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344117c080a7'
down_revision = '80da5235b382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_collab_message_ts', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coach_approved', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('approved_by_slack_uid', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('escalated', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.drop_column('escalated')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_slack_uid')
        batch_op.drop_column('coach_approved')
        batch_op.drop_column('slack_collab_message_ts')

    # ### end Alembic commands ###
