"""add lead availability tables

Revision ID: 3d34ea39db0f
Revises: 1b29976741b6
Create Date: 2026-07-25 20:21:07.159714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d34ea39db0f'
down_revision = '1b29976741b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_availability_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('message_ts', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_availability_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_nudged_at', sa.DateTime(), nullable=True),
    sa.Column('nudge_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['lead_availability_polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', name='uq_poll_participant')
    )
    op.create_table('lead_availability_poll_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['lead_availability_polls.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'emoji', name='uq_poll_emoji'),
    sa.UniqueConstraint('poll_id', 'practice_id', name='uq_poll_practice')
    )
    op.create_table('lead_availability_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('answered_for_date', sa.DateTime(), nullable=True),
    sa.Column('answered_for_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['lead_availability_polls.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'practice_id', 'user_id', name='uq_poll_practice_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_availability_responses')
    op.drop_table('lead_availability_poll_practices')
    op.drop_table('lead_availability_participants')
    op.drop_table('lead_availability_polls')
    # ### end Alembic commands ###
