"""Add updated_at column to UserSeason

Revision ID: 481438e8cbc5
Revises: d3309936c477
Create Date: 2025-11-27 22:56:46.418359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481438e8cbc5'
down_revision = 'd3309936c477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_seasons', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
