"""Add user_id to practice_leads

Revision ID: 4ff744fa0fd6
Revises: abc123456789
Create Date: 2025-12-28 00:32:20.606404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff744fa0fd6'
down_revision = 'abc123456789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_practice_leads_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_practice_leads_user_id', type_='foreignkey')
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
