"""add done_emoji snapshot to lead_availability_polls

Revision ID: 539ad532aeb3
Revises: b4d1f8e6c2a7
Create Date: 2026-07-26 10:24:31.486320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539ad532aeb3'
down_revision = 'b4d1f8e6c2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_availability_polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done_emoji', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_availability_polls', schema=None) as batch_op:
        batch_op.drop_column('done_emoji')

    # ### end Alembic commands ###
