"""phone_e164, verification tables, needs_review

Revision ID: 8055e0305cc4
Revises: a7c1e5f2b9d3
Create Date: 2026-08-23 06:08:52.570155

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8055e0305cc4'
down_revision = 'a7c1e5f2b9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_attempts_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_attempts_target'), ['target'], unique=False)

    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_email'), ['email'], unique=False)

    with op.batch_alter_table('user_seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_e164', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('phone_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sms_opt_out', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_phone_e164'), ['phone_e164'], unique=False)

    # ### end Alembic commands ###

    # Backfill phone_e164 from the legacy phone column (US numbers only).
    op.execute("""
        UPDATE users SET phone_e164 = sub.e164 FROM (
            SELECT id, '+1' || right(digits, 10) AS e164 FROM (
                SELECT id, regexp_replace(phone, '[^0-9]', '', 'g') AS digits
                FROM users WHERE phone IS NOT NULL AND phone <> ''
            ) d
            WHERE length(digits) = 10
               OR (length(digits) = 11 AND left(digits, 1) = '1')
        ) sub
        WHERE users.id = sub.id
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_e164'))
        batch_op.drop_column('sms_opt_out')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('phone_verified_at')
        batch_op.drop_column('phone_e164')

    with op.batch_alter_table('user_seasons', schema=None) as batch_op:
        batch_op.drop_column('needs_review')

    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_email'))

    op.drop_table('verification_codes')
    with op.batch_alter_table('verification_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_attempts_target'))
        batch_op.drop_index(batch_op.f('ix_verification_attempts_ip'))
        batch_op.drop_index(batch_op.f('ix_verification_attempts_created_at'))

    op.drop_table('verification_attempts')
    # ### end Alembic commands ###
