"""Add slack_log_message_ts to Practice

Revision ID: 80da5235b382
Revises: 5aa6b7c8d9e0
Create Date: 2025-12-29 01:56:38.988033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80da5235b382'
down_revision = '5aa6b7c8d9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_leads', schema=None) as batch_op:
        batch_op.drop_index('ix_practice_leads_user_id')

    with op.batch_alter_table('practice_rsvps', schema=None) as batch_op:
        batch_op.drop_index('ix_practice_rsvps_practice_id')
        batch_op.drop_index('ix_practice_rsvps_user_id')

    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_log_message_ts', sa.String(length=50), nullable=True))
        batch_op.drop_index('ix_practices_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.create_index('ix_practices_status', ['status'], unique=False)
        batch_op.drop_column('slack_log_message_ts')

    with op.batch_alter_table('practice_rsvps', schema=None) as batch_op:
        batch_op.create_index('ix_practice_rsvps_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_practice_rsvps_practice_id', ['practice_id'], unique=False)

    with op.batch_alter_table('practice_leads', schema=None) as batch_op:
        batch_op.create_index('ix_practice_leads_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
