"""Move social_location from practice_location to practice

Revision ID: 88225ae91b3d
Revises: c7d8e9f0a1b2
Create Date: 2026-01-02 16:24:07.986855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88225ae91b3d'
down_revision = 'c7d8e9f0a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_leads', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('practice_locations', schema=None) as batch_op:
        batch_op.drop_constraint('practice_locations_social_location_id_fkey', type_='foreignkey')
        batch_op.drop_column('social_location_id')

    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'social_locations', ['social_location_id'], ['id'])
        batch_op.drop_column('has_social')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_social', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('social_location_id')

    with op.batch_alter_table('practice_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('practice_locations_social_location_id_fkey', 'social_locations', ['social_location_id'], ['id'])

    with op.batch_alter_table('practice_leads', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
