"""Move social_location from practice_location to practice

Revision ID: 88225ae91b3d
Revises: c7d8e9f0a1b2
Create Date: 2026-01-02 16:24:07.986855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88225ae91b3d'
down_revision = 'c7d8e9f0a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    with op.batch_alter_table('practice_leads', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # Only drop social_location_id from practice_locations if it exists
    # (it may not exist in production if the column was never added there)
    result = conn.execute(sa.text("""
        SELECT column_name FROM information_schema.columns
        WHERE table_name = 'practice_locations' AND column_name = 'social_location_id'
    """))
    if result.fetchone():
        with op.batch_alter_table('practice_locations', schema=None) as batch_op:
            # Check if constraint exists before dropping
            constraint_result = conn.execute(sa.text("""
                SELECT constraint_name FROM information_schema.table_constraints
                WHERE table_name = 'practice_locations'
                AND constraint_name = 'practice_locations_social_location_id_fkey'
            """))
            if constraint_result.fetchone():
                batch_op.drop_constraint('practice_locations_social_location_id_fkey', type_='foreignkey')
            batch_op.drop_column('social_location_id')

    # Add social_location_id to practices if it doesn't exist
    result = conn.execute(sa.text("""
        SELECT column_name FROM information_schema.columns
        WHERE table_name = 'practices' AND column_name = 'social_location_id'
    """))
    if not result.fetchone():
        with op.batch_alter_table('practices', schema=None) as batch_op:
            batch_op.add_column(sa.Column('social_location_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('practices_social_location_id_fkey', 'social_locations', ['social_location_id'], ['id'])

    # Drop has_social column if it exists
    result = conn.execute(sa.text("""
        SELECT column_name FROM information_schema.columns
        WHERE table_name = 'practices' AND column_name = 'has_social'
    """))
    if result.fetchone():
        with op.batch_alter_table('practices', schema=None) as batch_op:
            batch_op.drop_column('has_social')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_social', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('social_location_id')

    with op.batch_alter_table('practice_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('practice_locations_social_location_id_fkey', 'social_locations', ['social_location_id'], ['id'])

    with op.batch_alter_table('practice_leads', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
