"""Add AppConfig table and slack_coach_summary_ts column

Revision ID: affb7c8eff3d
Revises: 88225ae91b3d
Create Date: 2026-01-08 19:07:40.988750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affb7c8eff3d'
down_revision = '88225ae91b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_coach_summary_ts', sa.String(length=50), nullable=True))

    # Seed default practice days config
    op.execute("""
        INSERT INTO app_config (key, value, description, category, created_at, updated_at)
        VALUES (
            'practice_days',
            '[{"day": "tuesday", "time": "18:00", "active": true}, {"day": "thursday", "time": "18:00", "active": true}, {"day": "saturday", "time": "09:00", "active": true}]',
            'Expected practice days and default times for weekly coach summary',
            'practices',
            NOW(),
            NOW()
        )
        ON CONFLICT (key) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.drop_column('slack_coach_summary_ts')

    # ### end Alembic commands ###
