"""add events tables

Revision ID: b433791f5783
Revises: d8b2c6f4a901
Create Date: 2026-07-24 21:06:38.473219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b433791f5783'
down_revision = 'd8b2c6f4a901'
branch_labels = None
depends_on = None


def _table_exists(table_name):
    return sa.inspect(op.get_bind()).has_table(table_name)


def _column_exists(table_name, column_name):
    return any(
        column["name"] == column_name
        for column in sa.inspect(op.get_bind()).get_columns(table_name)
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('signup_start', sa.DateTime(), nullable=False),
    sa.Column('signup_end', sa.DateTime(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('details_url', sa.String(length=500), nullable=True),
    sa.Column('discount_code', sa.String(length=255), nullable=True),
    sa.Column('custom_questions', sa.JSON(), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_slug'), ['slug'], unique=True)

    op.create_table('event_price_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('member_price_cents', sa.Integer(), nullable=True),
    sa.Column('participant_roles', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('price_option_id', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('discount_applied', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['price_option_id'], ['event_price_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role_label', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if _table_exists('payments'):
        with op.batch_alter_table('payments', schema=None) as batch_op:
            batch_op.add_column(sa.Column('event_registration_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_payments_event_registration_id', 'event_registrations', ['event_registration_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if (
        _table_exists('payments')
        and _column_exists('payments', 'event_registration_id')
    ):
        with op.batch_alter_table('payments', schema=None) as batch_op:
            batch_op.drop_constraint('fk_payments_event_registration_id', type_='foreignkey')
            batch_op.drop_column('event_registration_id')

    op.drop_table('event_participants')
    op.drop_table('event_registrations')
    op.drop_table('event_price_options')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_slug'))

    op.drop_table('events')
    # ### end Alembic commands ###
