"""add last_slack_activity to slack_users

Revision ID: b62e16189188
Revises: e5380715d447
Create Date: 2026-05-11 10:34:11.944008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62e16189188'
down_revision = 'e5380715d447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_slack_activity', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_users', schema=None) as batch_op:
        batch_op.drop_column('last_slack_activity')

    # ### end Alembic commands ###
