"""add logistics_notes and slack_details_ts to practices

Revision ID: e36bbec59bde
Revises: a7c3f9d2e1b8
Create Date: 2026-06-04 16:19:24.997354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36bbec59bde'
down_revision = 'a7c3f9d2e1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logistics_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('slack_details_ts', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.drop_column('slack_details_ts')
        batch_op.drop_column('logistics_notes')

    # ### end Alembic commands ###
