"""empty message

Revision ID: fca3ce6932b0
Revises: 
Create Date: 2025-04-21 10:24:07.092819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca3ce6932b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_technique', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tshirt_size', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ski_experience', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_email', sa.String(length=255), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('emergency_contact_email')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_relation')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('ski_experience')
        batch_op.drop_column('tshirt_size')
        batch_op.drop_column('preferred_technique')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
