// scripts/ui_audit/surfaces.mjs
// Every admin surface to capture, and the interactive states to reveal on each.
//
// This list is deliberate rather than crawled so the exact set of interactions is
// reviewable. Every `click` is an opener -- a selector that reveals UI. Nothing that
// submits, saves, deletes, runs, or sends belongs here, and capture.mjs aborts every
// non-GET request as a backstop.
//
// Most admin markup is generated by template literals in app/static/admin_*.js,
// not by the Jinja templates, so the selectors below were read out of that JS and
// then verified against the running app. Every one matches at capture time; a
// `SKIP ... no match for` line in a run means this file has drifted from the code.
//
// State fields:
//   name      -- becomes the screenshot filename segment
//   click     -- the opener
//   pre       -- clicks needed to reach the opener (e.g. open a drawer first)
//   viewports -- restrict to some viewports; omit for all three
//
// Surface field `longList: true` is the ONLY licence capture.mjs gives a base
// shot to lose content to a height cap. Set it only where everything past the
// cap is genuinely the same row repeating, and say why. Every other surface is
// captured whole, and a surface that outgrows the safety cap fails the run.

export const VIEWPORTS = [
  { name: 'desktop', width: 1440, height: 900 },
  { name: 'tablet', width: 1024, height: 768 },
  { name: 'mobile', width: 390, height: 844 },
];

// Concrete ids, chosen against the seeded database:
//   user 1     -- ACTIVE, has notes, a season, payments and tags (the dense
//                 variant of user_detail.html; most users render fewer blocks)
//   practice 19 -- dated today and inside an availability poll, so both the
//                 Skipper evaluation button and a populated #lead-picker render
//   trip 2      -- active, upcoming
//   season 5    -- the one with is_current = true
//   event 2     -- active, 2 price options, 3 registrations across 3 statuses
export const SURFACES = [
  {
    group: 'shared',
    name: 'dashboard',
    path: '/admin',
    states: [
      // The trigger lives in an `lg:hidden` header, so it is display:none at
      // 1024px and up. Captured once here rather than on every surface -- the
      // panel is the same partial everywhere.
      { name: 'mobile-nav', click: '#mobile-sidebar-open', viewports: ['mobile'] },
    ],
  },

  // ---- members ----------------------------------------------------------
  {
    group: 'members',
    name: 'users-list',
    // 266 identical .mr-row entries; 55,862 CSS px tall on mobile. Everything
    // below the cap is another roster row.
    longList: true,
    path: '/admin/users',
    states: [
      // The row handler ignores clicks that land on an `a` or `button`, so the
      // avatar is the reliable target rather than the row itself.
      { name: 'row-drawer', click: '#member-roster-list .mr-row:nth-child(1) .mr-avatar' },
      { name: 'quick-edit-modal', click: '#member-roster-list .mr-row:nth-child(1) .mr-edit-btn' },
      {
        name: 'tag-modal',
        pre: ['#member-roster-list .mr-row:nth-child(1) .mr-avatar'],
        click: '.admin-ui-drawer .mr-drawer-action-sm',
      },
      { name: 'role-filter-menu', click: '#mr-role-btn' },
      { name: 'select-mode', click: '#mr-select-toggle' },
      {
        name: 'bulk-bar',
        pre: ['#mr-select-toggle'],
        click: '#member-roster-list .mr-row:nth-child(1) .mr-select-cb',
      },
      { name: 'view-alumni', click: '.mr-pill[data-view="alumni"]' },
      { name: 'view-waitlist', click: '.mr-pill[data-view="waitlist"]' },
      { name: 'chip-unlinked-slack', click: '.mr-qf-chip[data-chip="unlinked-slack"]' },
    ],
  },
  {
    group: 'members',
    name: 'user-detail',
    path: '/admin/users/1',
    states: [],
  },
  {
    group: 'members',
    name: 'user-edit',
    path: '/admin/users/1/edit',
    states: [
      // showDeleteModal() only toggles classes; the delete POST is behind the
      // submit button inside the modal, which is never clicked.
      { name: 'delete-modal', click: 'button[onclick="showDeleteModal()"]' },
    ],
  },
  {
    group: 'members',
    name: 'roles',
    path: '/admin/roles',
    states: [
      { name: 'role-editor', click: '#rs-list .rs-row:nth-child(1)' },
      { name: 'new-role-draft', click: '#rs-new-btn' },
      // Below 768px the editor opens in a drawer instead of filling #rs-editor,
      // which stays display:none. Same component, two containers, so two states.
      {
        name: 'gradient-picker',
        pre: ['#rs-list .rs-row:nth-child(1)'],
        click: '#rs-editor .rs-swatches .rs-swatch:nth-child(3)',
        viewports: ['desktop', 'tablet'],
      },
      {
        name: 'gradient-picker-drawer',
        pre: ['#rs-list .rs-row:nth-child(1)'],
        click: '.admin-ui-drawer .rs-swatches .rs-swatch:nth-child(3)',
        viewports: ['mobile'],
      },
    ],
  },

  // ---- payments ---------------------------------------------------------
  {
    group: 'payments',
    name: 'payments',
    // 367 identical .pw-row-item entries across four sections; 38,887 CSS px
    // tall on mobile. All four section headers are above the cap.
    longList: true,
    path: '/admin/payments',
    states: [
      // .pw-row-main only -- the row's action zone holds Accept/Refund, and
      // Playwright hovers before clicking, which un-hides them.
      { name: 'row-drawer', click: '#pw-section-captured .pw-row-item:nth-child(1) .pw-row-main' },
      // The Closed section is the one collapsed by default.
      { name: 'closed-section', click: '.pw-sec-header[aria-controls="pw-section-closed"] .pw-sec-title' },
      {
        name: 'bulk-bar',
        click: '#pw-section-captured .pw-row-item:nth-child(1) .pw-row-check input[type="checkbox"]',
      },
      // "Capturable only" filters to status === requires_capture. It does not
      // capture anything -- the name is misleading, the behaviour is a filter.
      { name: 'filter-capturable', click: '#pw-filter-mount .admin-ui-pill' },
    ],
  },

  // ---- slack ops --------------------------------------------------------
  {
    group: 'slack',
    name: 'slack-sync',
    // 238 identical .ss-row entries; 32,277 CSS px tall on mobile. The tabs,
    // toolbar and first rows are all above the cap.
    longList: true,
    path: '/admin/slack',
    states: [
      { name: 'tab-all-db', click: '#ssync-tab-all_db' },
      // slack_users is empty, so this tab is the populated-vs-empty contrast.
      { name: 'tab-unclaimed-empty', click: '#ssync-tab-unclaimed_slack' },
      { name: 'row-drawer', click: '#ssync-list .ss-row .ss-row-name' },
      // The aria-label filter matters: an unqualified .ss-act-primary can also
      // be the one-click "confident match" link button, which POSTs.
      { name: 'link-picker', click: '#ssync-list button.ss-act-primary[aria-label*="to Slack"]' },
      { name: 'overflow-menu', click: '#ssync-list button.ss-overflow-btn' },
      { name: 'message-modal', click: '#ssync-msg-btn' },
      {
        name: 'drawer-picker',
        pre: ['#ssync-list .ss-row .ss-row-name'],
        click: '.admin-ui-drawer__body .ss-picker-input',
      },
    ],
  },
  {
    group: 'slack',
    name: 'channel-sync',
    path: '/admin/channel-sync',
    // Every control that reveals new UI on this page is a sync run. #results-section
    // is only un-hidden after a completed real sync, so it is unreachable safely.
    states: [],
  },
  {
    group: 'slack',
    name: 'scheduled-tasks',
    path: '/admin/scheduled-tasks',
    // Job cards render flat and already expanded; the only buttons are triggers.
    states: [],
  },
  {
    group: 'slack',
    name: 'skipper',
    path: '/admin/skipper/',
    states: [{ name: 'card-drawer', click: '#sk-feed .sk-card' }],
  },

  // ---- practices --------------------------------------------------------
  {
    group: 'practices',
    name: 'practices-list',
    path: '/admin/practices/',
    states: [
      { name: 'row-drawer', click: '#pl-list .pl-row' },
      // A draft practice's drawer additionally renders the .pl-draft-note block.
      { name: 'row-drawer-draft', click: '#pl-list .pl-row:has(.pl-draft)' },
      { name: 'past-expanded', click: '#pl-past-toggle' },
      // The button labelled "Cancel" only opens #cancel-modal; the POST is
      // behind the modal's own "Cancel Practice" button.
      { name: 'cancel-modal', pre: ['#pl-list .pl-row'], click: '#pl-cancel-btn' },
    ],
  },
  {
    group: 'practices',
    name: 'practices-calendar',
    path: '/admin/practices/calendar',
    states: [{ name: 'next-month', click: '#next-month' }],
  },
  {
    group: 'practices',
    name: 'practices-detail',
    path: '/admin/practices/19',
    states: [
      // GET-only; renders the rail evaluation blocks.
      { name: 'evaluation', click: '#evaluation-container button' },
      // Client-side selection only; also repopulates #plan-reaction-rows.
      { name: 'activity-selected', click: '#activities-pills .pe-pill' },
    ],
  },
  {
    group: 'practices',
    name: 'practices-new',
    path: '/admin/practices/new',
    // Create mode: single-column, no rail, and the older pill lead picker
    // (#leads-pills) instead of the detail page's ranked #lead-picker -- a real
    // layout variant, see the create/edit split note in detail.html.
    states: [
      { name: 'coach-selected', click: '#coaches-pills .person-pill' },
      // /people/data fills this from users tagged PRACTICES_LEAD. It rendered
      // empty until the audit database gained those tags; it now has 7 people.
      { name: 'lead-selected', click: '#leads-pills .person-pill' },
      // Pure opener: the handler only calls Model.setAddOpen(state, true) and
      // re-renders. The catalog is built from every activity's and workout
      // type's default_plan_reactions, so it only has options at all now that
      // the audit database configures activity defaults. Create mode is where
      // it is reachable -- with no activities selected nothing is inherited, so
      // canAdd() is true and #add-plan-reaction is visible.
      { name: 'plan-reaction-catalog', click: '#add-plan-reaction' },
    ],
  },
  {
    group: 'practices',
    name: 'practices-config',
    path: '/admin/practices/config',
    states: [
      // Locations is the default tab, so it is already the base shot.
      { name: 'tab-activities', click: '#tab-btn-activities' },
      { name: 'tab-types', click: '#tab-btn-types' },
      { name: 'tab-social-locations', click: '#tab-btn-social-locations' },
      { name: 'tab-settings', click: '#tab-btn-settings' },
      { name: 'tab-status-reference', click: '#tab-btn-status-reference' },
      // cfgAddDraft prepends an unsaved card. It focuses the name field, but a
      // create POST only fires on blur with a non-empty name, and nothing types.
      { name: 'location-draft', click: '#add-location-btn' },
      { name: 'map-preview', click: '#cfg-locations-list .cfg-card:first-of-type .cfg-map-toggle' },
      {
        name: 'day-defaults',
        pre: ['#tab-btn-settings'],
        click: '#settings-tab button[onclick="toggleDefaults(0)"]',
      },
    ],
  },

  // ---- catalog ----------------------------------------------------------
  {
    group: 'catalog',
    name: 'trips',
    path: '/admin/trips',
    states: [
      // .tl-db (the date block) avoids the card's own links and .tl-edit, which
      // stopPropagation and navigate away.
      { name: 'row-drawer', click: '#trips-rows .tl-cards .tl-card:first-child .tl-db' },
      { name: 'past-expanded', click: '#trips-list .tl-past-toggle' },
      // No trip has status "closed", so this pill renders the empty state.
      { name: 'filter-closed-empty', click: '.tl-pill[data-status="closed"]' },
    ],
  },
  {
    group: 'catalog',
    name: 'trip-new',
    path: '/admin/trips/new',
    states: [{ name: 'single-price', click: '#single-price' }],
  },
  {
    group: 'catalog',
    name: 'trip-edit',
    path: '/admin/trips/2/edit',
    states: [{ name: 'single-price', click: '#single-price' }],
  },
  {
    group: 'catalog',
    name: 'seasons',
    path: '/admin/seasons',
    states: [
      { name: 'hero-drawer', click: '#stl-hero .stl-hero-actions button' },
      { name: 'node-drawer', click: '#stl-list .stl-node .stl-card-body' },
      // stlActivate opens a confirm dialog and only POSTs once #stl-confirm-ok
      // resolves the promise true. The opener never reaches the write.
      { name: 'activate-confirm', click: '#stl-list .stl-node .stl-card-actions button' },
      {
        name: 'late-link-modal',
        pre: ['#stl-hero .stl-hero-actions button'],
        click: '.admin-ui-dw-footer button.admin-ui-dw-btn-ghost',
      },
    ],
  },
  {
    group: 'catalog',
    name: 'season-new',
    path: '/admin/seasons/new',
    states: [],
  },
  {
    group: 'catalog',
    name: 'season-edit',
    path: '/admin/seasons/5/edit',
    states: [],
  },
  {
    group: 'catalog',
    name: 'events',
    path: '/admin/events',
    states: [{ name: 'sorted-by-name', click: '#admin-events-grid .ae-sort[data-sort="name"]' }],
  },
  {
    group: 'catalog',
    name: 'event-new',
    path: '/admin/events/new',
    states: [
      // Both append an empty row to a client-side array and re-render. No fetch,
      // no submit -- the hidden JSON fields are only read on save.
      { name: 'price-option-row', click: '#add-price-option' },
      { name: 'question-row', click: '#add-question' },
    ],
  },
  {
    group: 'catalog',
    name: 'event-edit',
    path: '/admin/events/2/edit',
    states: [
      { name: 'price-option-row', click: '#add-price-option' },
      { name: 'question-row', click: '#add-question' },
    ],
  },
  {
    group: 'catalog',
    name: 'event-registrations',
    path: '/admin/events/2/registrations',
    states: [{ name: 'sorted', click: '#registration-grid-head .aer-sort' }],
  },
  {
    group: 'catalog',
    name: 'newsletter-prompts',
    path: '/admin/newsletter/prompts',
    states: [
      // Item 1 is auto-selected on load, so item 2 is the state change. It also
      // renders the disabled "Reset to File Default" variant (no file default).
      { name: 'prompt-quiet-week', click: '#prompt-list .prompt-item:nth-child(2)' },
    ],
  },
];
